### ISSUE TITLE
Team Manager

### ISSUE THREAD

**Issue by giovanniorigins** [missions-me/missions#491]
https://realtimeboard.com/app/board/o9J_k08qBW4=/

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/24/17 - 04/25/17
Work session total: 1:59:29
Grand total: 1:59:29

**Comment by giovanniorigins** [comment]
To access the team Manager: Dashboard -> Groups -> Team Manager button under Managers List

Things to consider:
- Group Names (referenced by position in array) will change when adding new groups, ie. Group 1 will become Group 2
- The 'Teams' tab may need to be the default over reservations. Creating a new team  brings the whole component to life.
-

**Comment by nkeena** [comment]
Yes, I think teams tab should be the default tab. Maybe once we have a team created we could automatically switch to the reservations tab or have a link somewhere "Add members" that also opens the reservation tab.

**Comment by nkeena** [comment]
### Teams API Details

##### Get All Teams

```json
GET /api/teams HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
    "data": [
        {
            "id": "ad417b30-51b1-48f4-b26d-0b6ed956c4d3",
            "callsign": "Team #1",
            "created_at": "2017-04-25 16:26:15",
            "updated_at": "2017-04-25 16:26:15",
            "deleted_at": null,
            "links": [
                {
                    "rel": "self",
                    "uri": "api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3"
                }
            ]
        }
    ],
    "meta": {
        "pagination": {
            "total": 1,
            "count": 1,
            "per_page": 10,
            "current_page": 1,
            "total_pages": 1,
            "links": []
        }
    }
}
```

##### Get Specific Team

```json
GET /api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3 HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
    "data": {
        "id": "ad417b30-51b1-48f4-b26d-0b6ed956c4d3",
        "callsign": "Team #1",
        "created_at": "2017-04-25 16:26:15",
        "updated_at": "2017-04-25 16:26:15",
        "deleted_at": null,
        "links": [
            {
                "rel": "self",
                "uri": "api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3"
            }
        ]
    }
}
```

##### Create Team

```json
POST /api/teams HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"callsign": "Team #1"
}
```

Errors:
```json
{
  "message": "422 Unprocessable Entity",
  "errors": {
    "callsign": [
      "The callsign field is required."
    ]
  }
}
```

##### Update Team

```json
PUT /api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3 HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"callsign": "Team #2"
}
```

Rules:
```php
$rules = [
    'callsign' => 'required|string',
];

if ($this->isMethod('put')) {
    $rules['callsign'] = 'sometimes|required|string';
}

return $rules;
```

**Comment by nkeena** [comment]
### Team Squads (Groups) API Details

##### All Squads

```json
GET /api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3/squads HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
    "data": [
        {
            "id": "0e023d92-6640-4514-9a2e-5e3ec16df476",
            "team_id": "ad417b30-51b1-48f4-b26d-0b6ed956c4d3",
            "callsign": "Group #1",
            "links": [
                {
                    "rel": "self",
                    "uri": "api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3/squads/0e023d92-6640-4514-9a2e-5e3ec16df476"
                }
            ]
        },
        {
            "id": "9cf251b5-bfb5-4413-9bb1-5a3311b1d555",
            "team_id": "ad417b30-51b1-48f4-b26d-0b6ed956c4d3",
            "callsign": "Group #2",
            "links": [
                {
                    "rel": "self",
                    "uri": "api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3/squads/9cf251b5-bfb5-4413-9bb1-5a3311b1d555"
                }
            ]
        }
    ]
}
```

##### Specific Squad

```json
GET /api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3/squads/0e023d92-6640-4514-9a2e-5e3ec16df476 HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
    "data": {
        "id": "0e023d92-6640-4514-9a2e-5e3ec16df476",
        "team_id": "ad417b30-51b1-48f4-b26d-0b6ed956c4d3",
        "callsign": "Group #1",
        "links": [
            {
                "rel": "self",
                "uri": "api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3/squads/0e023d92-6640-4514-9a2e-5e3ec16df476"
            }
        ]
    }
}
```

##### Create Squad

```json
POST /api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3/squads HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"callsign": "Group #1"
}
```

##### Update Squad

```json
PUT /api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3/squads/0e023d92-6640-4514-9a2e-5e3ec16df476 HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"callsign": "Group #1A",
	"team_id": "eb317c30-61b1-78g4-b26d-0b8ed100c4f3 (will move to different team)"
}
```

Rules:
```php
$rules = [
    'callsign' => 'sometimes|required|string',
    'team_id'  => 'sometimes|required|string|exists:teams,id'
];

if ($this->isMethod('post')) {
    $rules['callsign'] = 'required|string';
}

return $rules;
```

##### Delete Squad

```
DELETE /api/teams/ad417b30-51b1-48f4-b26d-0b6ed956c4d3/squads/0e023d92-6640-4514-9a2e-5e3ec16df476 HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache
```

**Comment by nkeena** [comment]
### Squad (Team Groups) Members API Details

##### All Members

```json
GET /api/squads/786b2de0-d536-4672-8b06-936ff7890ca8/members HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
    "data": [
        {
            "id": "0005a7ea-f92f-371e-878a-d28423ea2cfb",
            "given_names": "Edmund Jessy",
            "surname": "Wolff",
            "gender": "male",
            "status": "single",
            "age": 25,
            "avatar": "http://missions.dev/api/images/avatars/1n1d17-red-400x400.jpg",
            "desired_role": {
                "code": "MDSP",
                "name": "Medical Student: Pre-Med"
            },
            "leader": false,
            "created_at": "2017-04-25 19:52:44",
            "updated_at": "2017-04-25 19:52:44",
            "links": [
                {
                    "rel": "self",
                    "uri": "/api/reservations/0005a7ea-f92f-371e-878a-d28423ea2cfb"
                }
            ]
        },
        {
            "id": "00416f73-599a-336a-92ac-f0ea69c00aeb",
            "given_names": "Idell Kelsi",
            "surname": "O'Reilly",
            "gender": "male",
            "status": "single",
            "age": 37,
            "avatar": "http://missions.dev/api/images/avatars/1n1d17-dark-400x400.jpg",
            "desired_role": {
                "code": "MDSN",
                "name": "Medical Student: Nursing"
            },
            "leader": false,
            "created_at": "2017-04-25 19:52:44",
            "updated_at": "2017-04-25 19:52:44",
            "links": [
                {
                    "rel": "self",
                    "uri": "/api/reservations/00416f73-599a-336a-92ac-f0ea69c00aeb"
                }
            ]
        }
    ]
}
```

##### Specific Member
```
GET /api/squads/786b2de0-d536-4672-8b06-936ff7890ca8/members/0005a7ea-f92f-371e-878a-d28423ea2cfb HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
    "data": {
        "id": "0005a7ea-f92f-371e-878a-d28423ea2cfb",
        "given_names": "Edmund Jessy",
        "surname": "Wolff",
        "gender": "male",
        "status": "single",
        "age": 25,
        "avatar": "http://missions.dev/api/images/avatars/1n1d17-red-400x400.jpg",
        "desired_role": {
            "code": "MDSP",
            "name": "Medical Student: Pre-Med"
        },
        "leader": false,
        "created_at": "2017-04-25 19:52:44",
        "updated_at": "2017-04-25 19:52:44",
        "links": [
            {
                "rel": "self",
                "uri": "/api/reservations/0005a7ea-f92f-371e-878a-d28423ea2cfb"
            }
        ]
    }
}
```

##### Add Member(s)

Add single member by providing reservation id:
```json
POST /api/squads/786b2de0-d536-4672-8b06-936ff7890ca8/members HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"id": "00a42f65-37f0-3465-886d-4c4882b70e39",
	"leader": false
}
```

Add multiple members by providing an array of reservation ids like so:
```json
POST /api/squads/786b2de0-d536-4672-8b06-936ff7890ca8/members HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"members": [
		{
			"id": "0005a7ea-f92f-371e-878a-d28423ea2cfb",
			"leader": true
		},
		{
			"id": "00416f73-599a-336a-92ac-f0ea69c00aeb",
			"leader": false
		}
	]
}
```

##### Update Member

```json
PUT /api/squads/786b2de0-d536-4672-8b06-936ff7890ca8/members/0005a7ea-f92f-371e-878a-d28423ea2cfb HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"leader": true
}
```

##### Delete Member

```json
DELETE /api/squads/786b2de0-d536-4672-8b06-936ff7890ca8/members/0005a7ea-f92f-371e-878a-d28423ea2cfb HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache
```

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/25/17 - 04/26/17
Work session total: 7:48:19
Grand total: 9:47:48

**Comment by nkeena** [comment]
### API Details for Associating Groups and Campaigns with Teams

#### Adding Groups and Campaigns

Expected Response:
```
201 Created
```

**Method 1:** Add associations on team creation

```json
POST /api/teams HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"callsign": "Team #4",
	"associations": [
		{
			"type": "groups",
			"id": "ef08785b-308f-333e-8734-6b02725c4d03"
		},
		{
			"type": "campaigns",
			"id": "b304fd5a-3c18-4a77-9722-e6138f3429d7"
		}
	]
}
```

**Method 2:** Add associations after team creation

Add groups:
```json
POST /api/teams/b6854873-867e-421c-a977-929c2c10787d/groups HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"ids": ["02d2d742-6c63-3039-9ccf-d8f2464da1cd", "1b7adb98-4b8e-391b-b474-b99a972440ce"]
}
```

Add campaigns:
```json
POST /api/teams/b6854873-867e-421c-a977-929c2c10787d/campaigns HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"ids": ["b304fd5a-3c18-4a77-9722-e6138f3429d7"]
}
```

#### Removing Groups and Campaigns

Expected Response:
```
204 No Content
```

**Method 1:** Remove one association

Remove campaign:
```json
DELETE /api/teams/b6854873-867e-421c-a977-929c2c10787d/campaigns/b304fd5a-3c18-4a77-9722-e6138f3429d7 HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache
```

Remove group:
```json
DELETE /api/teams/b6854873-867e-421c-a977-929c2c10787d/groups/ef08785b-308f-333e-8734-6b02725c4d03 HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache
```

**Method 2:** Remove multiple associations

Remove campaigns:
```json
DELETE /api/teams/b6854873-867e-421c-a977-929c2c10787d/campaigns HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"ids": ["b304fd5a-3c18-4a77-9722-e6138f3429d7"]
}
```

Remove groups:
```json
DELETE /api/teams/b6854873-867e-421c-a977-929c2c10787d/groups HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache

{
	"ids": [
		"1b7adb98-4b8e-391b-b474-b99a972440ce", 
		"ef08785b-308f-333e-8734-6b02725c4d03"
	]
}
```

**Method 3:** Remove all associations

Remove all campaigns:
```json
DELETE /api/teams/b6854873-867e-421c-a977-929c2c10787d/campaigns HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache
```

Remove all groups:
```json
DELETE /api/teams/b6854873-867e-421c-a977-929c2c10787d/groups HTTP/1.1
Host: missions.dev
Content-Type: application/json
Cache-Control: no-cache
```

**Comment by giovanniorigins** [comment]
![image](https://cloud.githubusercontent.com/assets/1894949/25450068/ca10bd28-2a8b-11e7-84f4-1ebd1d1fb562.png)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/26/17 - 04/26/17
Work session total: 10:30:02
Grand total: 20:17:50

**Comment by nkeena** [comment]
Teams API is now available in the Wiki: https://github.com/missions-me/missions/wiki/Teams

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/27/17 - 04/27/17
Work session total: 1:00:29
Grand total: 21:18:19

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/27/17 - 04/28/17
Work session total: 4:15:04
Grand total: 25:33:23

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/29/17 - 04/29/17
Work session total: 0:07:12
Grand total: 25:40:35

**Comment by giovanniorigins** [comment]
**Outstanding Todos:**

- [ ] Scope teams to given group
- [ ] Scope teams to chosen campaign
- [ ] Add campaign chooser
- [ ] Add validation to prevent unapproved leadership roles from being added
    - Only leadership roles may be assigned as team leader / group leader
    - There is a `leadership()` method in the `TeamRole` utilities class that will only return leadership roles. I think we just need a route to it.

posted by @nkeena

**Comment by giovanniorigins** [comment]
@nkeena did you mean add campaign chooser to filters? or team create?

**Comment by nkeena** [comment]
@giovanniorigins I mean for team creation. Please see example on https://realtimeboard.com/app/board/o9J_k08qBW4=/

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/01/17 - 05/01/17
Work session total: 4:35:17
Grand total: 30:15:52

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/02/17 - 05/02/17
Work session total: 2:06:48
Grand total: 32:22:40

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/04/17 - 05/04/17
Work session total: 0:01:38
Grand total: 32:24:18

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/09/17 - 05/09/17
Work session total: 2:52:55
Grand total: 35:17:13

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/11/17 - 05/11/17
Work session total: 1:51:25
Grand total: 37:08:38

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/15/17 - 05/15/17
Work session total: 0:00:10
Grand total: 37:08:48

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/16/17 - 05/16/17
Work session total: 4:15:19
Grand total: 41:24:07

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/19/17 - 05/19/17
Work session total: 1:49:14
Grand total: 43:13:21

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/22/17 - 05/22/17
Work session total: 3:24:42
Grand total: 46:38:03

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/23/17 - 05/23/17
Work session total: 0:45:55
Grand total: 47:23:58
